import json
import os

base_dir = '/Users/emrekaramustafa/Desktop/projects/Cv Maker Pro +/assets/translations'

legal_translations = {
    'en': {
        'legal': {
            'privacy': {
                's1_heading': '1. Introduction',
                's1_body': 'Welcome to CV Maker Pro+ (the "App"). We are committed to protecting your privacy and ensuring you have a positive experience when you use our mobile application. This Privacy Policy outlines our data handling practices, particularly concerning the advanced AI and biometrics features we provide.',
                's2_heading': '2. Data We Collect and How We Use It',
                's2_body': 'To provide you with highly customized and professional resumes, we collect and process certain information:\n\n• Camera and Photo Library Access: We request access to your device\'s camera and photo library strictly to allow you to upload or capture a profile picture for your resume.\n\n• Biometric Data (Face Detection): We utilize on-device ML Kit Face Detection technology to automatically identify and properly crop faces in the photos you upload. This process happens entirely on your device. We do not transmit, collect, or store any biometric face data on our servers.\n\n• Resume Information: The text data you input (experience, education, skills, etc.) is temporarily processed to generate your final PDF document.',
                's3_heading': '3. Third-Party AI Processing (OpenAI)',
                's3_body': 'Our App leverages advanced artificial intelligence provided by OpenAI to analyze, enhance, and format your resume content. When you use our AI features (such as ATS score analysis or smart text rewriting), the text data you provide is securely sent to OpenAI\'s servers for processing. This data is only used to generate your requested response and is not used by OpenAI to train their models, in accordance with OpenAI\'s API data usage policies.',
                's4_heading': '4. In-App Purchases and Subscriptions',
                's4_body': 'We use RevenueCat to manage our in-app purchases and premium subscriptions securely. RevenueCat processes your purchase history anonymously to grant you access to premium features (like PDF downloads and AI tools) across your devices. We do not have access to your raw credit card information.',
                's5_heading': '5. Data Retention and Security',
                's5_body': 'Your privacy is our priority. Your generated resumes and entered data are primarily stored locally on your device. Any data transmitted to AI models is encrypted in transit and is only retained for as long as necessary to fulfill the immediate request. We do not sell, rent, or trade any of your personal information to third parties.',
                's6_heading': '6. Contact Us',
                's6_body': 'If you have any questions or concerns about this Privacy Policy or our data practices, please contact us at:\n\nmehmetemrekaramustafa@gmail.com',
            },
            'terms': {
                's1_heading': '1. Agreement to Terms',
                's1_body': 'By downloading or using CV Maker Pro+, you agree to be bound by these Terms of Use. If you disagree with any part of these terms, you may not access or use the application.',
                's2_heading': '2. License to Use',
                's2_body': 'We grant you a personal, non-exclusive, non-transferable, and revocable license to use the app for your personal, non-commercial purposes. You may not distribute, modify, reverse engineer, or create derivative works from the application.',
                's3_heading': '3. AI Features and Disclaimer',
                's3_body': 'Our app utilizes third-party artificial intelligence algorithms (such as OpenAI) to assist you in creating resumes. While we strive for accuracy, the AI-generated content may be incomplete, inaccurate, or require manual editing. You are solely responsible for reviewing and verifying any content generated by the AI before using it for professional applications.',
                's4_heading': '4. Subscriptions and Payments',
                's4_body': 'Some features of CV Maker Pro+ are available via an auto-renewing subscription or one-time purchases (In-App Purchases). Payments will be charged to your Apple ID or Google Play account at confirmation of purchase. Subscriptions automatically renew unless canceled at least 24 hours before the end of the current period. You can manage and cancel your subscriptions by going to your App Store or Google Play account settings after purchase.',
                's5_heading': '5. User Guidelines',
                's5_body': 'You agree not to use the app for any unlawful purposes or to upload any content that is offensive, defamatory, or violates any third party\'s rights.',
                's6_heading': '6. Contact Information',
                's6_body': 'If you have any questions regarding these Terms, please contact us at:\n\nmehmetemrekaramustafa@gmail.com',
            }
        }
    },
    'tr': {
        'legal': {
            'privacy': {
                's1_heading': '1. Giriş',
                's1_body': 'CV Maker Pro+ ("Uygulama")\na hoş geldiniz. Gizliliğinizi korumaya ve mobil uygulamamızı kullanırken olumlu bir deneyim yaşamanızı sağlamaya kararlıyız. Bu Gizlilik Politikası, özellikle sunduğumuz gelişmiş yapay zeka ve biyometrik özellikler açısından veri işleme uygulamalarımızı özetlemektedir.',
                's2_heading': '2. Topladığımız Veriler ve Kullanım Amacı',
                's2_body': 'Size özelleştirilmiş ve profesyonel özgeçmişler sunabilmek için belirli bilgileri topluyoruz:\n\n• Kamera ve Fotoğraf Kütüphanesi Erişimi: Yalnızca özgeçmişiniz için profil fotoğrafı yüklemenize veya çekmenize olanak tanımak amacıyla cihazınızın kamerasına ve fotoğraf kütüphanesine erişim talep ediyoruz.\n\n• Biyometrik Veri (Yüz Tespiti): Yüklediğiniz fotoğraflardaki yüzleri otomatik olarak tanımlamak ve kırpmak için cihaz üzerinde ML Kit Yüz Tanıma teknolojisinden yararlanıyoruz. Bu işlem tamamen cihazınızda gerçekleşir. Sunucularımızda hiçbir biyometrik yüz verisi iletilmez, toplanmaz veya saklanmaz.\n\n• Özgeçmiş Bilgileri: Girdiğiniz metin verileri (deneyim, eğitim, beceriler vb.) yalnızca nihai PDF belgesini oluşturmak için geçici olarak işlenir.',
                's3_heading': '3. Üçüncü Taraf Yapay Zeka İşleme (OpenAI)',
                's3_body': 'Uygulamamız, özgeçmiş içeriğinizi analiz etmek, geliştirmek ve biçimlendirmek için OpenAI tarafından sağlanan gelişmiş yapay zekadan yararlanmaktadır. Yapay zeka özelliklerimizi kullandığınızda (ATS skor analizi veya akıllı metin yeniden yazma gibi), sağladığınız metin verileri işlenmek üzere güvenli biçimde OpenAI sunucularına iletilir. Bu veriler yalnızca talep ettiğiniz yanıtı oluşturmak için kullanılır ve OpenAI\'nın API veri kullanım politikaları çerçevesinde modellerini eğitmek amacıyla kullanılmaz.',
                's4_heading': '4. Uygulama İçi Satın Almalar ve Abonelikler',
                's4_body': 'Uygulama içi satın almalarımızı ve premium aboneliklerimizi güvenli biçimde yönetmek için RevenueCat\'i kullanıyoruz. RevenueCat, cihazlarınız genelinde premium özelliklere (PDF indirme ve yapay zeka araçları gibi) erişiminizi sağlamak amacıyla satın alma geçmişinizi anonim olarak işler. Ham kredi kartı bilgilerinize erişim sağlamıyoruz.',
                's5_heading': '5. Veri Saklama ve Güvenlik',
                's5_body': 'Gizliliğiniz önceliğimizdir. Oluşturulan özgeçmişleriniz ve girdiğiniz veriler öncelikli olarak cihazınızda yerel olarak saklanır. Yapay zeka modellerine iletilen veriler aktarım sırasında şifrelenir ve yalnızca anlık talebi karşılamak için gereken süre boyunca tutulur. Kişisel bilgilerinizden hiçbirini üçüncü taraflara satmıyor, kiralamıyor veya devretmiyoruz.',
                's6_heading': '6. Bize Ulaşın',
                's6_body': 'Bu Gizlilik Politikası veya veri uygulamalarımız hakkında sorularınız veya endişeleriniz varsa lütfen bizimle iletişime geçin:\n\nmehmetemrekaramustafa@gmail.com',
            },
            'terms': {
                's1_heading': '1. Şartları Kabul',
                's1_body': 'CV Maker Pro+\'ı indirerek veya kullanarak bu Kullanım Koşullarına bağlı olmayı kabul edersiniz. Bu koşulların herhangi bir bölümüne katılmıyorsanız uygulamaya erişemez veya uygulamayı kullanamazsınız.',
                's2_heading': '2. Kullanım Lisansı',
                's2_body': 'Uygulamayı kişisel, ticari olmayan amaçlarla kullanmanız için size kişisel, münhasır olmayan, devredilemez ve iptal edilebilir bir lisans veriyoruz. Uygulamayı dağıtamaz, değiştiremez, tersine mühendislik yapamaz veya uygulamadan türev eserler oluşturamazsınız.',
                's3_heading': '3. Yapay Zeka Özellikleri ve Sorumluluk Reddi',
                's3_body': 'Uygulamamız, özgeçmiş oluşturmanıza yardımcı olmak için üçüncü taraf yapay zeka algoritmalarından (OpenAI gibi) yararlanmaktadır. Doğruluk için çaba göstersek de yapay zeka tarafından oluşturulan içerik eksik, hatalı olabilir veya manuel düzenleme gerektirebilir. Yapay zeka tarafından oluşturulan içerikleri profesyonel uygulamalarda kullanmadan önce incelemek ve doğrulamak tamamen sizin sorumluluğunuzdadır.',
                's4_heading': '4. Abonelikler ve Ödemeler',
                's4_body': 'CV Maker Pro+\'ın bazı özellikleri otomatik yenilenen abonelik veya tek seferlik satın almalar (Uygulama İçi Satın Almalar) aracılığıyla sunulmaktadır. Ödemeler, satın alma onayında Apple Kimliğinize veya Google Play hesabınıza tahakkuk ettirilir. Abonelikler, mevcut dönemin bitiminden en az 24 saat önce iptal edilmediği sürece otomatik olarak yenilenir. Satın alma sonrasında App Store veya Google Play hesap ayarlarınıza girerek aboneliklerinizi yönetebilir ve iptal edebilirsiniz.',
                's5_heading': '5. Kullanıcı Yönergeleri',
                's5_body': 'Uygulamayı herhangi bir yasadışı amaç için kullanmamayı veya rahatsız edici, iftira niteliğinde ya da üçüncü tarafların haklarını ihlal eden içerikler yüklememeyı kabul edersiniz.',
                's6_heading': '6. İletişim Bilgileri',
                's6_body': 'Bu Koşullarla ilgili sorularınız varsa lütfen bizimle iletişime geçin:\n\nmehmetemrekaramustafa@gmail.com',
            }
        }
    },
    'de': {
        'legal': {
            'privacy': {
                's1_heading': '1. Einleitung',
                's1_body': 'Willkommen bei CV Maker Pro+ (die „App"). Wir verpflichten uns, Ihre Privatsphäre zu schützen und Ihnen eine positive Erfahrung bei der Nutzung unserer mobilen Anwendung zu gewährleisten. Diese Datenschutzrichtlinie beschreibt unsere Datenverwaltungspraktiken, insbesondere im Hinblick auf die erweiterten KI- und Biometriefunktionen, die wir anbieten.',
                's2_heading': '2. Erhobene Daten und deren Verwendung',
                's2_body': 'Um Ihnen hochgradig individuelle und professionelle Lebensläufe bereitzustellen, erheben und verarbeiten wir bestimmte Informationen:\n\n• Kamera- und Fotomediathekzugriff: Wir fordern ausschließlich Zugriff auf die Kamera und Fotomediathek Ihres Geräts an, damit Sie ein Profilfoto für Ihren Lebenslauf hochladen oder aufnehmen können.\n\n• Biometrische Daten (Gesichtserkennung): Wir nutzen die gerätegebundene ML Kit-Gesichtserkennungstechnologie, um Gesichter in den hochgeladenen Fotos automatisch zu erkennen und korrekt zu beschneiden. Dieser Prozess findet vollständig auf Ihrem Gerät statt. Wir übermitteln, erfassen oder speichern keinerlei biometrische Gesichtsdaten auf unseren Servern.\n\n• Lebenslaufinformationen: Die von Ihnen eingegebenen Textdaten (Erfahrung, Ausbildung, Fähigkeiten usw.) werden vorübergehend verarbeitet, um Ihr endgültiges PDF-Dokument zu erstellen.',
                's3_heading': '3. KI-Verarbeitung durch Dritte (OpenAI)',
                's3_body': 'Unsere App nutzt die fortschrittliche künstliche Intelligenz von OpenAI, um Ihre Lebenslaufinhalte zu analysieren, zu verbessern und zu formatieren. Wenn Sie unsere KI-Funktionen verwenden (wie ATS-Analyse oder intelligentes Umschreiben von Texten), werden die von Ihnen bereitgestellten Textdaten sicher an OpenAIs Server zur Verarbeitung übertragen. Diese Daten werden ausschließlich zur Generierung der angeforderten Antwort verwendet und nicht genutzt, um die Modelle von OpenAI zu trainieren – gemäß der API-Datennutzungsrichtlinien von OpenAI.',
                's4_heading': '4. In-App-Käufe und Abonnements',
                's4_body': 'Wir verwenden RevenueCat, um unsere In-App-Käufe und Premium-Abonnements sicher zu verwalten. RevenueCat verarbeitet Ihren Kaufverlauf anonym, um Ihnen geräteübergreifend Zugang zu Premium-Funktionen (wie PDF-Downloads und KI-Tools) zu gewähren. Wir haben keinen Zugriff auf Ihre rohen Kreditkartendaten.',
                's5_heading': '5. Datenspeicherung und Sicherheit',
                's5_body': 'Ihre Privatsphäre hat oberste Priorität. Ihre erstellten Lebensläufe und eingegebenen Daten werden hauptsächlich lokal auf Ihrem Gerät gespeichert. Jegliche an KI-Modelle übertragenen Daten werden während der Übertragung verschlüsselt und nur so lange aufbewahrt, wie es zur Erfüllung der jeweiligen Anfrage notwendig ist. Wir verkaufen, vermieten oder handeln keinerlei Ihrer persönlichen Daten an Dritte.',
                's6_heading': '6. Kontakt',
                's6_body': 'Falls Sie Fragen oder Bedenken zu dieser Datenschutzrichtlinie oder unseren Datenpraktiken haben, kontaktieren Sie uns bitte unter:\n\nmehmetemrekaramustafa@gmail.com',
            },
            'terms': {
                's1_heading': '1. Zustimmung zu den Bedingungen',
                's1_body': 'Durch das Herunterladen oder die Nutzung von CV Maker Pro+ erklären Sie sich mit diesen Nutzungsbedingungen einverstanden. Wenn Sie mit einem Teil dieser Bedingungen nicht einverstanden sind, dürfen Sie die Anwendung nicht aufrufen oder nutzen.',
                's2_heading': '2. Nutzungslizenz',
                's2_body': 'Wir gewähren Ihnen eine persönliche, nicht exklusive, nicht übertragbare und widerrufliche Lizenz zur Nutzung der App für Ihre persönlichen, nicht kommerziellen Zwecke. Sie dürfen die Anwendung nicht verteilen, modifizieren, zurückentwickeln oder davon abgeleitete Werke erstellen.',
                's3_heading': '3. KI-Funktionen und Haftungsausschluss',
                's3_body': 'Unsere App nutzt KI-Algorithmen von Drittanbietern (wie OpenAI), um Ihnen bei der Erstellung von Lebensläufen zu helfen. Obwohl wir uns um Genauigkeit bemühen, können KI-generierte Inhalte unvollständig oder ungenau sein und eine manuelle Bearbeitung erfordern. Sie sind allein dafür verantwortlich, von der KI generierte Inhalte zu prüfen und zu verifizieren, bevor Sie diese für professionelle Bewerbungen verwenden.',
                's4_heading': '4. Abonnements und Zahlungen',
                's4_body': 'Einige Funktionen von CV Maker Pro+ sind über ein automatisch verlängertes Abonnement oder Einmalzahlungen (In-App-Käufe) verfügbar. Zahlungen werden bei Kaufbestätigung Ihrer Apple ID oder Ihrem Google Play-Konto belastet. Abonnements verlängern sich automatisch, sofern sie nicht mindestens 24 Stunden vor Ablauf des aktuellen Zeitraums gekündigt werden. Sie können Ihre Abonnements nach dem Kauf in den Einstellungen Ihres App Store- oder Google Play-Kontos verwalten und kündigen.',
                's5_heading': '5. Nutzerrichtlinien',
                's5_body': 'Sie stimmen zu, die App nicht für rechtswidrige Zwecke zu nutzen oder Inhalte hochzuladen, die beleidigend oder verleumderisch sind oder die Rechte Dritter verletzen.',
                's6_heading': '6. Kontaktinformationen',
                's6_body': 'Bei Fragen zu diesen Bedingungen kontaktieren Sie uns bitte unter:\n\nmehmetemrekaramustafa@gmail.com',
            }
        }
    },
    'fr': {
        'legal': {
            'privacy': {
                's1_heading': '1. Introduction',
                's1_body': 'Bienvenue sur CV Maker Pro+ (l\'« Application »). Nous nous engageons à protéger votre vie privée et à vous garantir une expérience positive lors de l\'utilisation de notre application mobile. Cette Politique de confidentialité décrit nos pratiques de gestion des données, notamment en ce qui concerne les fonctionnalités avancées d\'intelligence artificielle et de biométrie que nous proposons.',
                's2_heading': '2. Données collectées et leur utilisation',
                's2_body': 'Pour vous proposer des CV hautement personnalisés et professionnels, nous collectons et traitons certaines informations :\n\n• Accès à l\'appareil photo et à la photothèque : Nous demandons l\'accès à l\'appareil photo et à la photothèque de votre appareil uniquement pour vous permettre de télécharger ou de prendre une photo de profil pour votre CV.\n\n• Données biométriques (détection faciale) : Nous utilisons la technologie de détection faciale ML Kit sur l\'appareil pour identifier et recadrer automatiquement les visages dans les photos que vous téléchargez. Ce processus s\'effectue entièrement sur votre appareil. Nous ne transmettons, ne collectons ni ne stockons aucune donnée biométrique faciale sur nos serveurs.\n\n• Informations du CV : Les données textuelles que vous saisissez (expérience, formation, compétences, etc.) sont traitées temporairement pour générer votre document PDF final.',
                's3_heading': '3. Traitement par IA tiers (OpenAI)',
                's3_body': 'Notre application utilise l\'intelligence artificielle avancée d\'OpenAI pour analyser, améliorer et mettre en forme le contenu de votre CV. Lorsque vous utilisez nos fonctionnalités IA (comme l\'analyse du score ATS ou la réécriture intelligente de texte), les données textuelles que vous fournissez sont envoyées de manière sécurisée aux serveurs d\'OpenAI pour traitement. Ces données sont uniquement utilisées pour générer la réponse demandée et ne sont pas utilisées par OpenAI pour entraîner leurs modèles, conformément aux politiques d\'utilisation des données API d\'OpenAI.',
                's4_heading': '4. Achats intégrés et abonnements',
                's4_body': 'Nous utilisons RevenueCat pour gérer nos achats intégrés et abonnements premium de manière sécurisée. RevenueCat traite votre historique d\'achats de façon anonyme pour vous donner accès aux fonctionnalités premium (comme les téléchargements PDF et les outils IA) sur vos appareils. Nous n\'avons pas accès à vos informations de carte de crédit brutes.',
                's5_heading': '5. Conservation des données et sécurité',
                's5_body': 'Votre vie privée est notre priorité. Vos CV générés et les données saisies sont principalement stockés localement sur votre appareil. Toute donnée transmise aux modèles IA est chiffrée en transit et conservée uniquement le temps nécessaire pour répondre à la demande immédiate. Nous ne vendons, ne louons ni n\'échangeons aucune de vos informations personnelles à des tiers.',
                's6_heading': '6. Nous contacter',
                's6_body': 'Si vous avez des questions ou des préoccupations concernant cette Politique de confidentialité ou nos pratiques en matière de données, veuillez nous contacter à :\n\nmehmetemrekaramustafa@gmail.com',
            },
            'terms': {
                's1_heading': '1. Acceptation des conditions',
                's1_body': 'En téléchargeant ou en utilisant CV Maker Pro+, vous acceptez d\'être lié par ces Conditions d\'utilisation. Si vous n\'êtes pas d\'accord avec une partie de ces conditions, vous ne pouvez pas accéder à l\'application ni l\'utiliser.',
                's2_heading': '2. Licence d\'utilisation',
                's2_body': 'Nous vous accordons une licence personnelle, non exclusive, non transférable et révocable pour utiliser l\'application à des fins personnelles et non commerciales. Vous ne pouvez pas distribuer, modifier, désosser ou créer des œuvres dérivées de l\'application.',
                's3_heading': '3. Fonctionnalités IA et avertissement',
                's3_body': 'Notre application utilise des algorithmes d\'intelligence artificielle tiers (comme OpenAI) pour vous aider à créer des CV. Bien que nous nous efforcions d\'être précis, le contenu généré par l\'IA peut être incomplet, inexact ou nécessiter une modification manuelle. Vous êtes seul responsable de la vérification de tout contenu généré par l\'IA avant de l\'utiliser dans des candidatures professionnelles.',
                's4_heading': '4. Abonnements et paiements',
                's4_body': 'Certaines fonctionnalités de CV Maker Pro+ sont disponibles via un abonnement à renouvellement automatique ou des achats uniques (achats intégrés). Les paiements seront débités de votre identifiant Apple ou de votre compte Google Play lors de la confirmation de l\'achat. Les abonnements se renouvellent automatiquement sauf si vous les annulez au moins 24 heures avant la fin de la période en cours. Vous pouvez gérer et annuler vos abonnements dans les paramètres de votre compte App Store ou Google Play après l\'achat.',
                's5_heading': '5. Règles d\'utilisation',
                's5_body': 'Vous acceptez de ne pas utiliser l\'application à des fins illégales ou de ne pas télécharger de contenu offensant, diffamatoire ou portant atteinte aux droits de tiers.',
                's6_heading': '6. Informations de contact',
                's6_body': 'Si vous avez des questions concernant ces Conditions, veuillez nous contacter à :\n\nmehmetemrekaramustafa@gmail.com',
            }
        }
    },
    'es': {
        'legal': {
            'privacy': {
                's1_heading': '1. Introducción',
                's1_body': 'Bienvenido a CV Maker Pro+ (la «Aplicación»). Estamos comprometidos con la protección de su privacidad y con garantizarle una experiencia positiva al usar nuestra aplicación móvil. Esta Política de privacidad describe nuestras prácticas de gestión de datos, especialmente en lo que respecta a las funciones avanzadas de inteligencia artificial y biometría que ofrecemos.',
                's2_heading': '2. Datos que recopilamos y cómo los usamos',
                's2_body': 'Para ofrecerle currículums altamente personalizados y profesionales, recopilamos y procesamos cierta información:\n\n• Acceso a la cámara y a la biblioteca de fotos: Solicitamos acceso a la cámara y a la biblioteca de fotos de su dispositivo únicamente para permitirle cargar o tomar una foto de perfil para su currículum.\n\n• Datos biométricos (detección facial): Utilizamos la tecnología de detección facial ML Kit en el dispositivo para identificar y recortar automáticamente los rostros de las fotos que carga. Este proceso ocurre completamente en su dispositivo. No transmitimos, recopilamos ni almacenamos ningún dato biométrico facial en nuestros servidores.\n\n• Información del currículum: Los datos de texto que ingresa (experiencia, educación, habilidades, etc.) se procesan temporalmente para generar su documento PDF final.',
                's3_heading': '3. Procesamiento de IA por terceros (OpenAI)',
                's3_body': 'Nuestra aplicación utiliza la inteligencia artificial avanzada de OpenAI para analizar, mejorar y formatear el contenido de su currículum. Cuando usa nuestras funciones de IA (como el análisis de puntuación ATS o la reescritura inteligente de texto), los datos de texto que proporciona se envían de forma segura a los servidores de OpenAI para su procesamiento. Estos datos solo se usan para generar la respuesta solicitada y no son utilizados por OpenAI para entrenar sus modelos, de acuerdo con las políticas de uso de datos de la API de OpenAI.',
                's4_heading': '4. Compras dentro de la aplicación y suscripciones',
                's4_body': 'Usamos RevenueCat para gestionar de forma segura nuestras compras dentro de la aplicación y suscripciones premium. RevenueCat procesa su historial de compras de forma anónima para otorgarle acceso a funciones premium (como descargas de PDF y herramientas de IA) en todos sus dispositivos. No tenemos acceso a sus datos de tarjeta de crédito sin procesar.',
                's5_heading': '5. Retención de datos y seguridad',
                's5_body': 'Su privacidad es nuestra prioridad. Sus currículums generados y los datos ingresados se almacenan principalmente de forma local en su dispositivo. Cualquier dato transmitido a los modelos de IA está cifrado en tránsito y solo se conserva durante el tiempo necesario para cumplir con la solicitud inmediata. No vendemos, alquilamos ni intercambiamos ninguna de su información personal a terceros.',
                's6_heading': '6. Contáctenos',
                's6_body': 'Si tiene preguntas o inquietudes sobre esta Política de privacidad o nuestras prácticas de datos, contáctenos en:\n\nmehmetemrekaramustafa@gmail.com',
            },
            'terms': {
                's1_heading': '1. Aceptación de los términos',
                's1_body': 'Al descargar o usar CV Maker Pro+, acepta estar sujeto a estos Términos de uso. Si no está de acuerdo con alguna parte de estos términos, no podrá acceder ni usar la aplicación.',
                's2_heading': '2. Licencia de uso',
                's2_body': 'Le otorgamos una licencia personal, no exclusiva, intransferible y revocable para usar la aplicación con fines personales y no comerciales. No puede distribuir, modificar, realizar ingeniería inversa ni crear obras derivadas de la aplicación.',
                's3_heading': '3. Funciones de IA y aviso legal',
                's3_body': 'Nuestra aplicación utiliza algoritmos de inteligencia artificial de terceros (como OpenAI) para ayudarle a crear currículums. Aunque nos esforzamos por ser precisos, el contenido generado por IA puede estar incompleto, ser inexacto o requerir edición manual. Usted es el único responsable de revisar y verificar cualquier contenido generado por IA antes de usarlo en aplicaciones profesionales.',
                's4_heading': '4. Suscripciones y pagos',
                's4_body': 'Algunas funciones de CV Maker Pro+ están disponibles mediante una suscripción de renovación automática o compras únicas (compras dentro de la aplicación). Los pagos se cargarán a su Apple ID o cuenta de Google Play al confirmar la compra. Las suscripciones se renuevan automáticamente a menos que las cancele al menos 24 horas antes del final del período actual. Puede gestionar y cancelar sus suscripciones accediendo a la configuración de su cuenta de App Store o Google Play después de la compra.',
                's5_heading': '5. Pautas de uso',
                's5_body': 'Usted acepta no usar la aplicación para ningún propósito ilegal ni cargar contenido ofensivo, difamatorio o que viole los derechos de terceros.',
                's6_heading': '6. Información de contacto',
                's6_body': 'Si tiene preguntas sobre estos Términos, contáctenos en:\n\nmehmetemrekaramustafa@gmail.com',
            }
        }
    },
    'pt': {
        'legal': {
            'privacy': {
                's1_heading': '1. Introdução',
                's1_body': 'Bem-vindo ao CV Maker Pro+ (o «Aplicativo»). Estamos comprometidos em proteger sua privacidade e garantir uma experiência positiva ao usar nosso aplicativo móvel. Esta Política de Privacidade descreve nossas práticas de gestão de dados, especialmente em relação às funcionalidades avançadas de inteligência artificial e biometria que oferecemos.',
                's2_heading': '2. Dados coletados e como os usamos',
                's2_body': 'Para oferecer currículos altamente personalizados e profissionais, coletamos e processamos determinadas informações:\n\n• Acesso à câmera e à biblioteca de fotos: Solicitamos acesso à câmera e à biblioteca de fotos do seu dispositivo exclusivamente para permitir que você faça upload ou capture uma foto de perfil para seu currículo.\n\n• Dados biométricos (detecção facial): Utilizamos a tecnologia de detecção facial ML Kit no dispositivo para identificar e recortar automaticamente os rostos das fotos que você faz upload. Esse processo ocorre inteiramente no seu dispositivo. Não transmitimos, coletamos nem armazenamos nenhum dado facial biométrico em nossos servidores.\n\n• Informações do currículo: Os dados de texto inseridos por você (experiência, educação, habilidades, etc.) são processados temporariamente para gerar seu documento PDF final.',
                's3_heading': '3. Processamento de IA por terceiros (OpenAI)',
                's3_body': 'Nosso aplicativo utiliza a inteligência artificial avançada da OpenAI para analisar, aprimorar e formatar o conteúdo do seu currículo. Quando você usa nossos recursos de IA (como análise de pontuação ATS ou reescrita inteligente de texto), os dados de texto fornecidos são enviados com segurança aos servidores da OpenAI para processamento. Esses dados são usados apenas para gerar a resposta solicitada e não são utilizados pela OpenAI para treinar seus modelos, em conformidade com as políticas de uso de dados da API da OpenAI.',
                's4_heading': '4. Compras no aplicativo e assinaturas',
                's4_body': 'Usamos o RevenueCat para gerenciar com segurança nossas compras no aplicativo e assinaturas premium. O RevenueCat processa seu histórico de compras anonimamente para conceder acesso a recursos premium (como downloads de PDF e ferramentas de IA) em seus dispositivos. Não temos acesso aos seus dados brutos de cartão de crédito.',
                's5_heading': '5. Retenção de dados e segurança',
                's5_body': 'Sua privacidade é nossa prioridade. Seus currículos gerados e os dados inseridos são armazenados principalmente de forma local no seu dispositivo. Quaisquer dados transmitidos aos modelos de IA são criptografados em trânsito e retidos apenas pelo tempo necessário para atender à solicitação imediata. Não vendemos, alugamos nem negociamos nenhuma das suas informações pessoais com terceiros.',
                's6_heading': '6. Fale conosco',
                's6_body': 'Se tiver dúvidas ou preocupações sobre esta Política de Privacidade ou nossas práticas de dados, entre em contato conosco:\n\nmehmetemrekaramustafa@gmail.com',
            },
            'terms': {
                's1_heading': '1. Aceitação dos termos',
                's1_body': 'Ao baixar ou usar o CV Maker Pro+, você concorda em ficar vinculado a estes Termos de Uso. Se não concordar com qualquer parte destes termos, não poderá acessar ou usar o aplicativo.',
                's2_heading': '2. Licença de uso',
                's2_body': 'Concedemos a você uma licença pessoal, não exclusiva, intransferível e revogável para usar o aplicativo para fins pessoais e não comerciais. Você não pode distribuir, modificar, fazer engenharia reversa nem criar obras derivadas do aplicativo.',
                's3_heading': '3. Recursos de IA e aviso legal',
                's3_body': 'Nosso aplicativo utiliza algoritmos de inteligência artificial de terceiros (como a OpenAI) para ajudá-lo a criar currículos. Embora nos esforcemos pela precisão, o conteúdo gerado por IA pode estar incompleto, impreciso ou exigir edição manual. Você é o único responsável por revisar e verificar qualquer conteúdo gerado por IA antes de usá-lo em candidaturas profissionais.',
                's4_heading': '4. Assinaturas e pagamentos',
                's4_body': 'Alguns recursos do CV Maker Pro+ estão disponíveis por meio de uma assinatura de renovação automática ou compras únicas (compras no aplicativo). Os pagamentos serão cobrados no seu Apple ID ou na sua conta do Google Play na confirmação da compra. As assinaturas se renovam automaticamente a menos que sejam canceladas com pelo menos 24 horas de antecedência antes do término do período atual. Você pode gerenciar e cancelar suas assinaturas nas configurações da sua conta da App Store ou do Google Play após a compra.',
                's5_heading': '5. Diretrizes de uso',
                's5_body': 'Você concorda em não usar o aplicativo para fins ilegais nem fazer upload de conteúdo ofensivo, difamatório ou que viole os direitos de terceiros.',
                's6_heading': '6. Informações de contato',
                's6_body': 'Se tiver dúvidas sobre estes Termos, entre em contato conosco:\n\nmehmetemrekaramustafa@gmail.com',
            }
        }
    },
}

def deep_update(d, u):
    for k, v in u.items():
        if isinstance(v, dict):
            d[k] = deep_update(d.get(k, {}), v)
        else:
            d[k] = v
    return d

for lang, data in legal_translations.items():
    file_path = os.path.join(base_dir, f'{lang}.json')
    with open(file_path, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    existing = deep_update(existing, data)
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(existing, f, ensure_ascii=False, indent=4)
    print(f'Updated {lang}.json')
print('Done!')
