import 'package:share_plus/share_plus.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:pdfx/pdfx.dart';
import 'package:provider/provider.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/widgets/scale_button.dart';
import '../../presentation/providers/resume_provider.dart';
import '../../data/models/resume_model.dart';
import '../../data/services/pdf_generator_service.dart';
import '../../../paywall/presentation/pages/paywall_page.dart';
import '../../../paywall/presentation/providers/premium_provider.dart';

import 'home_page.dart';
import 'resume_edit_page.dart';

class PreviewPage extends StatefulWidget {
  final ResumeModel? resume;

  const PreviewPage({super.key, this.resume});

  @override
  State<PreviewPage> createState() => _PreviewPageState();
}

class _PreviewPageState extends State<PreviewPage> {
  final PdfGeneratorService _pdfService = PdfGeneratorService();
  String? _pdfPath;
  bool _isLoading = true;
  String? _errorMessage;
  PdfControllerPinch? _pdfController;

  @override
  void initState() {
    super.initState();
    _generatePdf();
  }

  @override
  void dispose() {
    _pdfController?.dispose();
    super.dispose();
  }

  Future<void> _generatePdf() async {
    setState(() {
      _isLoading = true;
      _errorMessage = null;
      _pdfController?.dispose();
      _pdfController = null;
    });

    try {
      final resume = context.read<ResumeProvider>().currentResume ?? widget.resume;

      if (resume == null) {
        if (mounted) {
          setState(() {
            _errorMessage = "No resume data available";
            _isLoading = false;
          });
        }
        return;
      }

      final file = await _pdfService.generateResumePdf(resume);
      if (mounted) {
        final controller = PdfControllerPinch(
          document: PdfDocument.openFile(file.path),
        );
        setState(() {
          _pdfPath = file.path;
          _pdfController = controller;
          _isLoading = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _errorMessage = e.toString();
          _isLoading = false;
        });
      }
    }
  }

  Future<bool> _openPaywall({bool forceNoClose = false}) async {
    final result = await Navigator.push<bool>(
      context,
      MaterialPageRoute(
        builder: (_) => PaywallPage(allowDismiss: !forceNoClose),
      ),
    );
    return result == true;
  }

  Future<void> _onSharePressed() async {
    final premium = context.read<PremiumProvider>();
    if (!premium.isPremium) {
      final purchased = await _openPaywall();
      if (!purchased || !mounted) return;
    }
    if (_pdfPath == null || !mounted) return;
    await SharePlus.instance.share(ShareParams(
      files: [XFile(_pdfPath!)],
      text: 'Check out my resume generated by CV Maker Pro +',
    ));
  }

  @override
  Widget build(BuildContext context) {
    final isPremium = context.watch<PremiumProvider>().isPremium;

    return Scaffold(
      backgroundColor: Colors.grey.shade300,
      appBar: AppBar(
        titleSpacing: 0,
        title: FittedBox(
          fit: BoxFit.scaleDown,
          alignment: Alignment.centerLeft,
          child: Text('form.preview'.tr(), style: const TextStyle(fontSize: 20)),
        ),
        backgroundColor: AppColorsDynamic.of(context).surface,
        foregroundColor: AppColorsDynamic.of(context).textPrimary,
        elevation: 0,
        actions: [
          // Template Switcher Button
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 8.0, horizontal: 2.0),
            child: PopupMenuButton<String>(
              tooltip: 'form.change_template'.tr(),
              position: PopupMenuPosition.under,
              onSelected: (value) {
                context.read<ResumeProvider>().switchTemplate(value);
                _generatePdf();
              },
              itemBuilder: (context) => [
                PopupMenuItem(value: 'modern',  child: Text('form.modern_template'.tr())),
                PopupMenuItem(value: 'classic', child: Text('form.classic_template'.tr())),
                PopupMenuItem(value: 'creative',child: Text('form.creative_template'.tr())),
                PopupMenuItem(value: 'elegant', child: Text('form.elegant_template'.tr())),
                PopupMenuItem(value: 'student', child: Text('form.linkedin_template'.tr())),
                PopupMenuItem(value: 'startup', child: Text('form.startup_template'.tr())),
                PopupMenuItem(value: 'british_green', child: Text('form.british_green_template'.tr())),
              ],
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                decoration: BoxDecoration(
                  color: AppColorsDynamic.of(context).textPrimary.withOpacity(0.1),
                  borderRadius: BorderRadius.circular(16),
                ),
                child: Row(
                  children: [
                    Icon(Icons.style_outlined, size: 18, color: AppColorsDynamic.of(context).textPrimary),
                    const SizedBox(width: 4),
                    Text(
                      'form.change_template'.tr(),
                      style: TextStyle(
                        color: AppColorsDynamic.of(context).textPrimary,
                        fontWeight: FontWeight.w600,
                        fontSize: 13,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
          
          // Share Button
          Padding(
            padding: const EdgeInsets.only(right: 12.0, top: 10.0, bottom: 10.0, left: 2.0),
            child: Stack(
              clipBehavior: Clip.none,
              alignment: Alignment.topRight,
              children: [
                SizedBox(
                  height: 36,
                  child: FilledButton.icon(
                    onPressed: _pdfPath == null ? null : _onSharePressed,
                    icon: const Icon(Icons.send_rounded, size: 16),
                    label: Text('common.send'.tr(), style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 13)),
                    style: FilledButton.styleFrom(
                      padding: const EdgeInsets.symmetric(horizontal: 12),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(16),
                      ),
                    ),
                  ),
                ),
                if (!isPremium)
                  Positioned(
                    top: -4,
                    right: -4,
                    child: Container(
                      width: 12,
                      height: 12,
                      decoration: BoxDecoration(
                        color: const Color(0xFFF59E0B),
                        shape: BoxShape.circle,
                        border: Border.all(color: AppColorsDynamic.of(context).surface, width: 2),
                      ),
                    ),
                  ),
              ],
            ),
          ),
        ],
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : _errorMessage != null
              ? Center(
                  child: Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const Icon(Icons.error_outline, size: 64, color: Colors.red),
                        const SizedBox(height: 16),
                        Text('common.pdf_error'.tr(args: ['']),
                            style: Theme.of(context).textTheme.titleLarge),
                        const SizedBox(height: 8),
                        Text(_errorMessage!, textAlign: TextAlign.center),
                        const SizedBox(height: 16),
                        FilledButton(
                          onPressed: _generatePdf,
                          child: Text('common.retry'.tr()),
                        ),
                      ],
                    ),
                  ),
                )
              : _pdfController == null
                  ? Center(child: Text('common.failed_generate_pdf'.tr()))
                  : Stack(
                      children: [
                        // PDF viewer — renders pages as images, full-width
                        PdfViewPinch(
                          controller: _pdfController!,
                          scrollDirection: Axis.vertical,
                          padding: 0,
                          builders: PdfViewPinchBuilders<DefaultBuilderOptions>(
                            options: const DefaultBuilderOptions(),
                            documentLoaderBuilder: (_) =>
                                const Center(child: CircularProgressIndicator()),
                            pageLoaderBuilder: (_) =>
                                const Center(child: CircularProgressIndicator()),
                          ),
                        ),
                        // Premium share banner at the bottom (free users only)
                        if (!isPremium)
                          Positioned(
                            bottom: 140,
                            left: 0,
                            right: 0,
                            child: _buildShareBanner(context),
                          ),

                        // Continue Editing Button
                        Positioned(
                          bottom: isPremium ? 130 : 80,
                          left: 20,
                          right: 20,
                          child: ScaleButton(
                            onTap: () {
                              if (Navigator.canPop(context)) {
                                Navigator.pop(context);
                              } else {
                                Navigator.pushAndRemoveUntil(
                                  context,
                                  MaterialPageRoute(builder: (_) => HomePage()),
                                  (route) => false,
                                );
                              }
                            },
                            child: Container(
                              height: 56,
                              decoration: BoxDecoration(
                                gradient: AppColorsDynamic.of(context).primaryGradient,
                                borderRadius: BorderRadius.circular(16),
                                boxShadow: [
                                  BoxShadow(
                                    color: AppColorsDynamic.of(context).primaryStart.withValues(alpha: 0.4),
                                    blurRadius: 15,
                                    offset: const Offset(0, 8),
                                  ),
                                ],
                              ),
                              child: Row(
                                mainAxisAlignment: MainAxisAlignment.center,
                                children: [
                                  const Icon(Icons.edit_note_rounded, color: Colors.white, size: 24),
                                  const SizedBox(width: 8),
                                  Text(
                                    'common.continue_editing'.tr(),
                                    style: const TextStyle(
                                      color: Colors.white,
                                      fontSize: 16,
                                      fontWeight: FontWeight.bold,
                                      letterSpacing: 0.5,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
    );
  }

  Widget _buildShareBanner(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topCenter,
          end: Alignment.bottomCenter,
          colors: [Colors.transparent, Color(0xFF0F172A)],
        ),
      ),
      padding: const EdgeInsets.fromLTRB(24, 32, 24, 28),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(
            'premium.share_cta'.tr(),
            style: const TextStyle(
                color: Colors.white,
                fontWeight: FontWeight.w700,
                fontSize: 15),
            textAlign: TextAlign.center,
          ),
          const SizedBox(height: 12),
          SizedBox(
            width: double.infinity,
            child: DecoratedBox(
              decoration: BoxDecoration(
                gradient: const LinearGradient(
                    colors: [Color(0xFFF59E0B), Color(0xFFF97316)]),
                borderRadius: BorderRadius.circular(14),
              ),
              child: ElevatedButton.icon(
                onPressed: _onSharePressed,
                icon: const Icon(Icons.share_rounded,
                    color: Colors.white, size: 18),
                label: Text('premium.share_unlock'.tr(),
                    style: const TextStyle(
                        color: Colors.white,
                        fontWeight: FontWeight.w700)),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.transparent,
                  shadowColor: Colors.transparent,
                  padding: const EdgeInsets.symmetric(vertical: 14),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(14)),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
